### ISSUE TITLE
Loaded iRacing but iRacing not connecting to code

### ISSUE THREAD

**Issue by CinnamonRage** [vipoo/iRacingSDK.Net#15]
I have created a little program but it never enters the for each loop as it says that iRacing is not connected. Has iRacing made updates that have broken this?

``` csharp
namespace iRacingTest
{
    using System;
    using System.Threading;
    using iRacingSDK;

    class Program
    {
        static void Main(string[] args)
        {
            var iRacing = new iRacingConnection();

            foreach (var data in iRacing
                .GetDataFeed()
                .WithCorrectedPercentages()
                .WithCorrectedDistances()
                .WithPitStopCounts())
            {
                Console.WriteLine(data.Telemetry.FuelLevel);
                Thread.Sleep(100);
            }
            
            Console.WriteLine("End");
        }
    }
}
```

Thanks for any help you can provide.

**Comment by CinnamonRage** [comment]
I am using v1.0.0.43 and .Net Core 3.1, for completness.

**Comment by CinnamonRage** [comment]
![image](https://user-images.githubusercontent.com/399311/92325097-ce1f8700-f03f-11ea-9abf-84a4ee042815.png)

**Comment by dwhood** [comment]
@CinnamonRage did you ever get this to work? I can access the sdk using linqpad, but when trying to use in a console application, a connection to iracing is never established.

**Comment by markjamesm** [comment]
I'm trying to use this SDK for a project and downloaded SDK version 1.0.0.43) from [NuGet](https://www.nuget.org/packages/iRacingSDK/1.0.0.43) and ran into the same connection errors. 

I decided to clone the repo and tried running the included sample app. iRacing is running (I'm in car), but the connection status is listed as "Not Connected":

![Not connected](https://user-images.githubusercontent.com/20845425/105927063-37b12980-6011-11eb-8801-62cbbc98905d.png)

Looking at the log messages (I would paste the text, but the errors scroll too fast to stop them), the error appears to be caused by line 124 of [Datafeed.cs](https://github.com/vipoo/iRacingSDK.Net/blob/master/DataFeed.cs#L124):

![Log message](https://user-images.githubusercontent.com/20845425/105926991-0b95a880-6011-11eb-9e8f-6d3888a9707e.png)

I set a breakpoint on line 124 and can see valid data from my current session (including the sessionInfoString):

![Debugger](https://user-images.githubusercontent.com/20845425/105927783-ae9af200-6012-11eb-9cfd-ec02e9f0c2b4.png)

There seems to be a related bug filed for Yaml Dotnet which I believe is causing an error with the parsing:

https://github.com/aaubry/YamlDotNet/issues/372

**Comment by MerlinCooper** [comment]
There have been issues with previous versions of the YAML.Net NuGet which caused the same issue. 

What version of YAML.net are you using? 

Suggest trying it with v5.3.1 - that's the one which is within the current NuGet and which I'm using in the iRacingReplayDirector as well. Works reliable.
