### ISSUE TITLE
Forked fix is not merged with master

### ISSUE THREAD

**Issue by Grimzentide** [vipoo/iRacingSDK.Net#8]
Hey Dean, any chance you can complete the merge even though you don't appear to be active in the iR community any more?

**Comment by vipoo** [comment]
sure - are you interested in taking ownership of this repo?

**Comment by MerlinCooper** [comment]
Hey Dean, if you are interested in transfering ownership I would offer to volunteer. 

Shouldn't be to much of an issue to keep the iRacingSKD and the nuget-package up-to date. But due to some changes in iRacing and YAML.Dot minor modifications had to be made which never have been merged back to the origin. 

![grafik](https://user-images.githubusercontent.com/3088879/80793029-3ba13f80-8b96-11ea-9d3f-9fa4cc51a429.png)

**Comment by vipoo** [comment]
Hi mate,

I appreciate you volunteering and would love to transfer this.

I would assume the real item is the nuget package - to keep the naming
clean - I dont know if others have created alternative named nuget packages.

I have added an issue to the repo - so that people can know whats
happening.  Feel free to add anything to it.
(https://github.com/vipoo/iRacingSDK.Net/issues/9)

If you send me your nuget account id, i can look at adding you as an owner

Cheers
Dean

**Comment by MerlinCooper** [comment]
Merged all changes made into the original repository vipoo/iRacingSDK.NET. 

Feel free to do more pull-requests - will try to keep it as up-to-date as possible. But please allow some work-days after triggering a pull-request.
