### ISSUE TITLE
Ownership

### ISSUE THREAD

**Issue by vipoo** [vipoo/iRacingSDK.Net#9]
Hi all,

I see there has been a bit of development on this code base - since i abandon it.

I would really like to transfer ownership of this repo and the nuget package (https://www.nuget.org/packages/iRacingSDK/) -- but i am not sure how/who wants/needs this - or do i just delete this?

@Herbstein and @MerlinCooper seem to be active contributors

And @MerlinCooper has volunteered ownership transfer

I guess the key transfer is nuget - as the owner can simply publish from their fork - and i delete my repo at some point.

I want to give it a good home - so unless I get an objection - i will discuss with @MerlinCooper about transfering ownership of repo and nuget package.

Cheers
Dean

**Comment by Herbstein** [comment]
Just for reference: I have no problem with Merlin Cooper taking over the ownership. I fixed and used it for a while, but am now using a custom SDK catering to my specific needs. Thanks for the work you put into this!

**Comment by MerlinCooper** [comment]
Hi Dean,

it would be ok for me if you just add me as additional contributor on the original github repository vipoo/iRacingSKD.NET because that in that way all forks would get updates - goal would be to merge the independet workstreams in one together and maybe get a larger userbase in the future. 

![grafik](https://user-images.githubusercontent.com/3088879/81114933-35f38300-8f23-11ea-9307-e946fce00b51.png)

If you prefere to [transfer the ownership of the repository](https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/) to my github account that would be fine for me as well. 

With regard to NuGet my UserID is MCooper and my understanding is that you will have to specifiy me as [additional package owner](https://devblogs.microsoft.com/nuget/managing-package-owners/). Afterwards I can remove you as package owner if you really want that. But I would be fine to just co-own / collaborate on the github / nuget repositories. 

By the way what are your planes with regard to the iRacingReplayOverlay.net? There are still people in the iRacing forum using it - but it would need a brush up for endurance races and very long replays as well.

**Comment by vipoo** [comment]
I have no plans for the iracing libraries.  You are also welcome if you want to facilitate its ongoing development.

**Comment by MerlinCooper** [comment]
@vipoo Trying to get the CI using AppVeyor for iRacingSKD.NET and iRacingReplayOverlay.NET running again. Having issues with the subprojects which appveyor can't find. 

Could you propably provide the appveyor configuration files (YAML) for those two projects. Would save me a lot of time. Thanks in advance.

**Comment by MerlinCooper** [comment]
@vipoo Trying to get the CI using AppVeyor for iRacingSKD.NET and iRacingReplayOverlay.NET running again. Having issues with the subprojects which appveyor can't find.

Could you propably provide the appveyor configuration files (YAML) for those two projects. Would save me a lot of time. Thanks in advance.

**Comment by vipoo** [comment]
Hi Mate,

Wow - i had completely forgotten i had used AppVeyor for this stuff - talk
about abandonware!

I am not sure why did not simply check in the yaml configs.

I have attached here.

The projects have been building in my account, with your recent changes -
the cloud, its always there!

Cheers
Dean

**Comment by MerlinCooper** [comment]
Hey Dean,

either I'm doing something wrong or the attached files did not get transfered to github. 

Could you please retry or simply add them to the repository? 

Thanks in advance.
Merlin

**Comment by vipoo** [comment]
Send me your email address - dean.netherton@gmail.com - and i will email them to ya

**Comment by MerlinCooper** [comment]
@hieblmedia

 Not sure how your remark is related to this issue and/or to the iRacingSDK.NET NuGet. Can you provide more detailed information please.
